"""
summarizer.py
--------------
Extractive summarization, same approach family as the Task 1 document
summarizer: score each sentence by its TF-IDF weight, keep the
highest-scoring N sentences in their original order.

Reusing this technique here (rather than calling an LLM to "summarize the
resume") keeps candidate summaries deterministic and free, and means the
Task 1 deliverable directly powers part of Task 2 — the summarizer earns
its keep twice.
"""

from __future__ import annotations

import re
from typing import List

from sklearn.feature_extraction.text import TfidfVectorizer


def _split_sentences(text: str) -> List[str]:
    """Lightweight sentence splitter — good enough for resume bullet points,
    which are rarely complex multi-clause prose.
    """
    text = re.sub(r"\s+", " ", text).strip()
    raw = re.split(r"(?<=[.!?])\s+|\n+", text)
    return [s.strip() for s in raw if len(s.strip()) > 15]


def summarize(text: str, num_sentences: int = 3) -> str:
    """Return the top `num_sentences` highest-TF-IDF-weighted sentences,
    in their original order (so the summary still reads coherently).
    """
    sentences = _split_sentences(text)
    if len(sentences) <= num_sentences:
        return " ".join(sentences)

    vectorizer = TfidfVectorizer(stop_words="english")
    try:
        tfidf_matrix = vectorizer.fit_transform(sentences)
    except ValueError:
        return " ".join(sentences[:num_sentences])

    sentence_scores = tfidf_matrix.sum(axis=1).A1  # sum of weights per sentence
    top_indices = sentence_scores.argsort()[::-1][:num_sentences]
    top_indices_sorted = sorted(top_indices)  # restore original order

    return " ".join(sentences[i] for i in top_indices_sorted)


def generate_recommendation(breakdown) -> str:
    """Deterministic, template-based recommendation text built from the
    ScoreBreakdown — same philosophy as the explanation() method: nothing
    here is generated by a model, so it can never contradict the numbers.

    To get more natural phrasing without losing this guarantee, pass these
    same facts into a local LLM (e.g. Ollama) as a *rewriting* step only —
    never let the LLM decide the facts themselves. See README for the
    suggested extension point.
    """
    if breakdown.final_score >= 0.75:
        verdict = "Strong match — recommended to shortlist."
    elif breakdown.final_score >= 0.5:
        verdict = "Moderate match — worth a closer look."
    else:
        verdict = "Weak match against this specific job description."

    parts = [verdict]
    if breakdown.missing_required_skills:
        parts.append(
            f"Key gap(s): {', '.join(breakdown.missing_required_skills[:3])}."
        )
    if breakdown.candidate_experience_years < breakdown.required_experience_years:
        parts.append(
            f"Has {breakdown.candidate_experience_years:.1f} of the "
            f"{breakdown.required_experience_years:.1f} years requested."
        )
    return " ".join(parts)
